apiVersion: v1
kind: Pod
metadata:
  name: grammar-pod
  labels:
    app: grammar-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
      livenessProbe:
        httpGet:
          path: /index.html
          port: 80
        initialDelaySeconds: 15
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
status: {}