apiVersion: v1
kind: Pod
metadata:
  name: healthcheck-pod
  namespace: cka-demo
spec:
  containers:
    - name: healthcheck-pod
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      imagePullPolicy: Always
      livenessProbe:
        httpGet:
        path: /
        port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
      readinessProbe:
        httpGet:
        path: /
        port: 80
        initialDelaySeconds: 3
        periodSeconds: 3

