apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
    - name: resoureces-pod
      image: nginx:1.14.2
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "0.5"
          memory: "500Mi"
      ports:
        - containerPort: 80