apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /home/NFS/nginx
    server: 192.168.116.101
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem