apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    env: dev
    tier: frontend
    track: stable
    version: "1.14.2"
    release: "1.0"
    owner: k8s
    team: devops
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80