apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: naginx-service
    env: dev
spec:
  selector:
      app: nginx
      env: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP