apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-flavor
                operator: In
                values:
                  - s3.large.2
                  - s3.large.3
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: node-flavor
                operator: In
                values:
                  - s3.large.2
  containers:
    - name: with-node-affinity
      image: k8s.gcr.io/pause:2.0