apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
    - name: private-reg-container
      image: venture007-docker.pkg.coding.net/cka/cka-docker/demo-vue:v1.0.0
  imagePullSecrets:
    - name: regcred