apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx:alpine
      name: container-0
      volumeMounts:
        - name: vol-secret              # 挂载名为vol-secret的Volume
          mountPath: "/tmp"
  imagePullSecrets:
    - name: default-secret
  volumes:
    - name: vol-secret
      secret:                         # 引用Secret
        secretName: mysecret