apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - image: nginx:alpine
      name: container-0
      env:
        - name: key
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: key1
  imagePullSecrets:
    - name: default-secret
