apiVersion: v1
kind: Pod
metadata:
  name: sa-example-pod
spec:
  serviceAccountName: sa-example
  containers:
    - image: nginx:alpine
      name: container-0
      resources:
        limits:
          cpu: 100m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 200Mi
  imagePullSecrets:
    - name: default-secret