apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-healing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-healing
  template:
    metadata:
      labels:
        app: nginx-healing
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
